import Phaser from 'phaser';
import { bridge, BridgeEvent } from '../../bridge';
import type { GardenSlot } from '../../types';

const STAGE_ORDER: Record<string, number> = { SEED: 0, SEEDLING: 1, GROWING: 2, MATURE: 3, BLOOMING: 4 };

export class GardenScene extends Phaser.Scene {
  private slots: GardenSlot[] = [];
  private flowerObjects: Map<number, Phaser.GameObjects.Container> = new Map();
  private potZones: Map<number, Phaser.GameObjects.Zone> = new Map();
  private activeTool: 'seed' | 'glove' | null = null;
  private bgImage: Phaser.GameObjects.Image | null = null;

  constructor() {
    super({ key: 'GardenScene' });
  }

  preload() {
    // Try loading background image (will be generated by SD)
    this.load.image('bg-garden', '/assets/bg-garden.png');
  }

  create() {
    const W = 1024, H = 768;

    // Background image (falls back to gradient if not found)
    this.bgImage = this.add.image(W / 2, H / 2, 'bg-garden').setDisplaySize(W, H).setAlpha(0.9);
    this.bgImage.on('loaderror', () => {
      // Fallback: gradient sky + grass
      this.add.rectangle(W / 2, 200, W, 400, 0x87ceeb);
      this.add.rectangle(W / 2, 500, W, 540, 0x4caf50);
      this.add.ellipse(120, 80, 120, 50, 0xffffff, 0.5);
      this.add.ellipse(400, 50, 90, 40, 0xffffff, 0.4);
      this.add.ellipse(750, 100, 130, 45, 0xffffff, 0.55);
      this.add.rectangle(W / 2, 205, W, 4, 0xa1887f);
      for (let i = 0; i < 6; i++) {
        this.add.rectangle(10 + i * 200, 225, 10, 50, 0x8d6e63);
      }
    });

    // Pot positions — 2 rows × 3 cols, centered
    const positions = [
      { x: 250, y: 330 }, { x: 512, y: 330 }, { x: 774, y: 330 },
      { x: 250, y: 560 }, { x: 512, y: 560 }, { x: 774, y: 560 },
    ];

    for (let idx = 0; idx < 6; idx++) {
      const p = positions[idx];

      // Dirt patch
      this.add.ellipse(p.x, p.y + 18, 90, 35, 0x8B4513, 0.9);
      this.add.ellipse(p.x, p.y + 15, 80, 28, 0x6B3410, 0.5);

      // Terracotta pot
      this.add.rectangle(p.x, p.y, 52, 38, 0xa0522d);
      this.add.rectangle(p.x, p.y - 18, 56, 8, 0xc97142);
      this.add.rectangle(p.x, p.y + 18, 46, 6, 0x8B4513);

      // Interactive zone
      const zone = this.add.zone(p.x, p.y - 15, 75, 90).setInteractive({ useHandCursor: true });
      zone.setDepth(5);
      this.potZones.set(idx, zone);

      zone.on('pointerover', () => {
        zone.setAlpha(0.12);
        if (this.activeTool) {
          this.input.setDefaultCursor(this.activeTool === 'seed' ? 'cell' : 'pointer');
        }
      });
      zone.on('pointerout', () => {
        zone.setAlpha(0);
        this.input.setDefaultCursor('default');
      });
      zone.on('pointerdown', () => {
        const slot = this.slots.find((s: GardenSlot) => s.position === idx);
        const flower = slot?.flower || null;
        bridge.emit(BridgeEvent.POT_CLICKED, {
          position: idx,
          flowerId: flower?.id || null,
          flower,
        });
      });
    }

    // Title
    this.add.text(W / 2, 25, '🌺 你的花园', {
      fontSize: '22px', color: '#ffffff', fontFamily: 'Arial',
      stroke: '#2d5a27', strokeThickness: 4,
    }).setOrigin(0.5).setDepth(20);

    this.setupBridgeListeners();
    console.log('🌻 GardenScene ready (full-screen)');
  }

  private getSlotCenter(position: number) {
    const positions = [
      { x: 250, y: 330 }, { x: 512, y: 330 }, { x: 774, y: 330 },
      { x: 250, y: 560 }, { x: 512, y: 560 }, { x: 774, y: 560 },
    ];
    return positions[position] || { x: 512, y: 445 };
  }

  private createFlowerObject(slot: GardenSlot) {
    const { x, y } = this.getSlotCenter(slot.position);
    const flower = slot.flower;
    if (!flower) return;

    const container = this.add.container(x, y - 85);
    container.setDepth(10);

    // If flower has an AI-generated image URL, load and display it
    if (flower.imageUrl) {
      // Use a unique key per flower
      const imgKey = `flower-img-${flower.id}`;
      if (!this.textures.exists(imgKey)) {
        this.load.image(imgKey, flower.imageUrl);
        this.load.once(`filecomplete-image-${imgKey}`, () => {
          // Replace container children with the loaded image
          container.removeAll(true);
          const img = this.add.image(0, 0, imgKey).setDisplaySize(80, 120);
          container.add(img);
          this.addNameLabel(container, flower);
        });
        this.load.start();
      }
      // In the meantime, show a simple placeholder
      this.addPlaceholderFlower(container, flower);
    } else {
      // Geometric placeholder
      this.addPlaceholderFlower(container, flower);
    }

    container.setSize(70, 130);
    container.setInteractive();
    this.flowerObjects.set(slot.position, container);
  }

  private addPlaceholderFlower(container: Phaser.GameObjects.Container, flower: any) {
    const stemHMap: Record<string, number> = { SEED: 0, SEEDLING: 18, GROWING: 40, MATURE: 60, BLOOMING: 75 };
    const sH = stemHMap[flower.stage] || 35;
    const rarityColors: Record<string, number> = { N: 0x808080, R: 0x4488ff, SR: 0xaa44ff, SSR: 0xffaa00, UR: 0xff3333 };
    const color = rarityColors[flower.rarity] || 0x808080;

    if (flower.stage !== 'SEED') {
      container.add(this.add.rectangle(0, -sH / 2, 5, sH, 0x2e7d32).setOrigin(0.5));
    }

    if (['GROWING', 'MATURE', 'BLOOMING'].includes(flower.stage)) {
      const leafY = -20;
      container.add(this.add.ellipse(-14, leafY, 22, 9, 0x43a047));
      container.add(this.add.ellipse(14, leafY, 22, 9, 0x43a047));
    }

    const crownY = -sH;
    if (flower.stage === 'SEED') {
      container.add(this.add.circle(0, 2, 6, 0x8B4513));
    } else {
      const crownSize = flower.stage === 'BLOOMING' ? 16 : flower.stage === 'MATURE' ? 12 : 8;
      for (let i = 0; i < 7; i++) {
        const angle = (i / 7) * Math.PI * 2;
        container.add(this.add.circle(
          Math.cos(angle) * crownSize * 0.7,
          crownY + Math.sin(angle) * crownSize * 0.5,
          crownSize * 0.45, color, 0.85
        ));
      }
      container.add(this.add.circle(0, crownY, crownSize * 0.3, 0xffee58));
      if (flower.rarity !== 'N') {
        container.add(this.add.circle(0, crownY - crownSize - 8, 7, color, 0.35));
      }
    }

    this.addNameLabel(container, flower);
  }

  private addNameLabel(container: Phaser.GameObjects.Container, flower: any) {
    const name = flower.name || '花';
    container.add(this.add.text(0, 30, name, {
      fontSize: '9px', color: '#fff', fontFamily: 'Arial',
      stroke: '#000', strokeThickness: 2, align: 'center',
    }).setOrigin(0.5));

    const stageEmojis: Record<string, string> = { SEED: '🌰', SEEDLING: '🌱', GROWING: '🌿', MATURE: '🌼', BLOOMING: '🌸' };
    container.add(this.add.text(0, 42, stageEmojis[flower.stage] || '', {
      fontSize: '12px', align: 'center',
    }).setOrigin(0.5));
  }

  private refreshSlots(slots: GardenSlot[]) {
    // Sort slots so higher-stage flowers render on top
    this.slots = [...slots].sort((a, b) => {
      const stageA = STAGE_ORDER[a.flower?.stage || ''] ?? -1;
      const stageB = STAGE_ORDER[b.flower?.stage || ''] ?? -1;
      return stageA - stageB;
    });

    this.flowerObjects.forEach((c) => c.destroy());
    this.flowerObjects.clear();

    for (const slot of slots) {
      if (slot.flower) this.createFlowerObject(slot);
    }
  }

  private setupBridgeListeners() {
    bridge.on(BridgeEvent.REFRESH_GARDEN, (slots: GardenSlot[]) => {
      this.refreshSlots(slots);
    });
    bridge.on(BridgeEvent.TOOL_ACTIVATED, (payload: { tool: 'seed' | 'glove' | null }) => {
      this.activeTool = payload.tool;
      if (payload.tool === 'glove') {
        this.input.setDefaultCursor('pointer');
      } else if (payload.tool === 'seed') {
        this.input.setDefaultCursor('cell');
      } else {
        this.input.setDefaultCursor('default');
      }
    });
  }
}
